export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
